### ISSUE TITLE
Provide pre-commit hooks

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/fortitude#375]
@LiamPattinson, sorry for commenting in a closed PR. I also use pre-commit in my work. It would be nice if Fortitude could be used as a pre-commit hook. I assume there's some tricks to make this happen, for example running a local hook... But it would be really nice if it was possible to add something like this to my `.pre-commit-config.yaml`:

```
  - repo: https://github.com/PlasmaFAIR/fortitude
    rev: v0.7.0
    hooks:
      - id: fortitude
```

Is it appropriate to create a separate issue on this?

_Originally posted by @stigh in https://github.com/PlasmaFAIR/fortitude/issues/361#issuecomment-2729298531_
